language: python
sudo: false
python:
  - "2.7"
env:
  - TOXENV="py27-django18"
  - TOXENV="py27-django19"
  - TOXENV="py34-django18"
  - TOXENV="py34-django19"
install: pip install tox
script: tox -e $TOXENV
