language: python
sudo: false

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION="stable/1.11.x"
  - DJANGO_VERSION="stable/2.0.x"
  - DJANGO_VERSION="stable/2.1.x"
  - DJANGO_VERSION="stable/2.2.x"
  - DJANGO_VERSION="stable/3.0.x"
  - DJANGO_VERSION="stable/3.1.x"

install:
   # This is a dependency of our Django test script
 - pip install argparse

   # Install the dependencies of the app itself
   # - pip install -r requirements.txt

   # Clone Django from the GitHub repository
 - git clone -b $DJANGO_VERSION --single-branch https://github.com/django/django
 - pip install -e django/
 - pip install -e .
 - pip install -r django_resized/testapp/requirements.txt

 - pip install 'coverage>=3,<5'

 - pip install flake8

before_script:
    - flake8 django_resized --ignore=E501

script:
    - coverage run runtests.py

after_success:
 - pip install coveralls
 - coveralls

matrix:
  exclude:
    - python: 3.5
      env: DJANGO_VERSION="stable/3.0.x"
    - python: 3.5
      env: DJANGO_VERSION="stable/3.1.x"
    - python: 3.8
      env: DJANGO_VERSION="stable/1.11.x"
    - python: 3.8
      env: DJANGO_VERSION="stable/2.0.x"
    - python: 3.8
      env: DJANGO_VERSION="stable/2.1.x"
    - python: 3.8
      env: DJANGO_VERSION="stable/2.2.x"
